---
title: "Data Cleaning and Manipulation"
output: html_document
author: Anastasija Mensikova
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = FALSE, message = FALSE}
library(dplyr)
library(tidyr)

# To call stats filter -- stats::filter()
```

## Reformat the catch data

* Remove "all" column
* Remove "notes" column
* Create a "species" column
    - Move from wide to long
* General QA

[Mike Byerly. Alaska commercial salmon catches by management region (1886- 1997). Gulf of Alaska Data Portal. df35b.304.2.](https://knb.ecoinformatics.org/view/df35b.304.2)

```{r}
catch_original = read.csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", stringsAsFactors = FALSE)
regions_original = read.csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.303.1")
head(catch_original)
```

### Remove the "all" and "notesRegCode" columns using "select"
```{r}
#Cmd + shift + m: pipe operator shortcut ( %>% )

# catch_long = catch_original %>% select(-All, -notesRegCode) %>% ... --> this will be the same

catch_long = catch_original %>% select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum) %>% 
                                gather(key = "species", value = "catch", -Region, -Year)

head(catch_long)
```

```{r}
catch_wide = catch_long %>% spread(key = species, value = catch)

head(catch_wide)
```



## Join the region definitions

## Miscellaneous functions

